steps:
  - name: 'gcr.io/cloud-builders/go'
    env:
      - 'PROJECT_ROOT=github.com/heptio/ark'
    args:
      - test
      - ./...

  - name: 'gcr.io/cloud-builders/go'
    env:
      - 'PROJECT_ROOT=github.com/heptio/ark'
    args:
      - install
      - -ldflags
      - "-X github.com/heptio/ark/pkg/buildinfo.Version=${BRANCH_NAME} -X github.com/heptio/ark/pkg/buildinfo.GitSHA=${COMMIT_SHA} -X github.com/heptio/ark/pkg/buildinfo.GitTreeState=clean"
      - ./cmd/ark

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ark:${BRANCH_NAME}', '.']

images:
  - gcr.io/$PROJECT_ID/ark:${BRANCH_NAME}
